apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: todoapp
    application: todoapp
    service: todoapp
    template: springboot-eap-persistent
  name: todoapp-h2-claim
  namespace: todo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
