spring:
  profiles: eap-persistent
  datasource:
    jndi-name: ${TODO_JNDI}
---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:${user.home}/todo;AUTO_SERVER=TRUE;
---
server:
  port: ${SERVER_PORT}
spring:
  profiles: persistent
  datasource:
    url: ${TODO_DATABASE_URL}
    username: ${TODO_USERNAME}
    password: ${TODO_PASSWORD}
---
spring:
  h2:
   console:
    enabled: true
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   generate-ddl: false